<script type="text/javascript" src="{{url('Frontend/Assests/js/jquery-2.1.4.min.js')}}"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/Modernizr.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/lightbox.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/masonry.pkgd.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/isotope.pkgd.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/jquery.parallax-1.1.3.js"></script>
    <script type="text/javascript" src="{{url('Frontend/Assests/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/masonry.js"></script>
	<script type="text/javascript" src="{{url('Frontend/Assests/js/functions.js"></script>